### ISSUE TITLE
method "destroyDocuments" fails

### ISSUE THREAD

**Issue by mugi-luffy** [elastic/app-search-node#30]
- app-serach-node version: 7.9.0
- System: ubuntu 20.04.1
- node version: v14.5.0

when calling:
`client.destroyDocuments(engine, documentIds)`

I got the following error:
```
.../node_modules/@elastic/app-search-node/lib/client.js:24
  if (responseBody.errors) {
                   ^

TypeError: Cannot read property 'errors' of undefined
```
I then tried fixing the problem by adding a test for undefined in client.js before line 24 like this:
`if (!responseBody) return []`

It seemed to work but I got the following error:
```
Error: Http method DELETE is not supported by this URL
    at Request._callback (.../node_modules/@elastic/app-search-node/lib/client.js:96:26)
    at Request.self.callback .../node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> .../node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (.../node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1226:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errorMessages: []
```
Using Postman to delete the documents worked without issue!

**Comment by mugi-luffy** [comment]
The solution is to make sure http 1.1 is used. (in my case changed the nginx configuration)
In http 1.0 delete requests can't have a body, which causes the error

**Comment by JasonStoltz** [comment]
Great, thank you for following up 👍
